"""ReAct reasoning loop for Roma.

Inspired by OpenJarvis NativeReActAgent
(src/openjarvis/core/agents/native_react.py).

ReAct = Thought → Action → Observation → repeat → Final Answer.

Handles complex multi-step queries that a single builder can't answer:
  "compare April with March, find which queue drove the change, forecast 30 days"
  "show severity breakdown then tell me which agents need coaching"

When a local LLM is available the Thought step is generated by the model;
otherwise a keyword planner picks the next action automatically.
"""

from __future__ import annotations

import re
from typing import Any

MAX_STEPS = 6       # safety ceiling
THOUGHT_BUDGET = 4  # max LLM calls per query


# ── Action registry ────────────────────────────────────────────────────────────

# Maps action-name → regex that triggers it.
# Keep this in sync with engine._BUILDERS.
_ACTION_PATTERNS: dict[str, str] = {
    "kpis":          r"kpi|tnps|nps|csat|promoter|score",
    "forecast":      r"forecast|predict|next.*day|future",
    "waterfall":     r"waterfall|monthly.nps|gained|lost",
    "top_bottom":    r"top.*bottom|best.*worst|ranked.queue",
    "agent_ranking": r"agent.rank|peer.bench|percentile",
    "pattern":       r"hour|day of week|pattern|timing",
    "channel_fcr":   r"channel|fcr|first.call",
    "velocity":      r"velocity|spike|jumped",
    "toxic_combos":  r"toxic|combo|root.cause",
    "winback":       r"win.?back|churn|recover",
    "severity":      r"severity|critical|urgent",
    "cohort":        r"cohort|recovery.rate",
    "compare":       r"\bvs\b|versus|compare",
    "print_top":     r"print|show|table|ranked.by|top.detractor",
    "detractors":    r"detractor|unhappy|complaint",
    "trend":         r"trend|over.time|rising|falling",
    "segments":      r"segment|cluster|group|persona",
    "drivers":       r"driv|influenc|what.*caus|why|factor",
    "summary":       r"what.*know|overview|summary|data",
    "stats":         r"stat|mean|correlat|distribution",
    "repeat":        r"repeat|recurring|multiple.times",
    "alerts":        r"alert|changed|anything.new|notable",
    "export":        r"export|save|excel|pptx|presentation",
}


def _detect_actions(text: str) -> list[str]:
    """Return action names whose trigger pattern matches text (ordered by pattern)."""
    q = text.lower()
    return [name for name, pat in _ACTION_PATTERNS.items() if re.search(pat, q)]


# ── Simple keyword planner (no-LLM path) ─────────────────────────────────────

def _plan_steps(question: str) -> list[str]:
    """
    Break a compound question into an ordered list of action names.

    Approach:
    - Split on logical connectors ("then", "and", "also", "after that").
    - For each fragment, detect which action it wants.
    - De-duplicate while preserving order.
    """
    fragments = re.split(
        r"\bthen\b|\band\b|\balso\b|\bafter\s+that\b|\bfinally\b"
        r"|\bmoreover\b|\bplus\b|\bكمان\b|\bثم\b|\bبعدين\b",
        question.lower(),
    )
    seen: set[str] = set()
    steps: list[str] = []
    for frag in fragments:
        for act in _detect_actions(frag):
            if act not in seen:
                seen.add(act)
                steps.append(act)
    return steps or _detect_actions(question)


# ── LLM-guided thought generator ─────────────────────────────────────────────

_REACT_SYSTEM = """\
You are a reasoning assistant for Roma, an offline CX analytics tool.
Available actions: {actions}.
Given the user question and any observations so far, output either:
  Thought: <one sentence rationale>
  Action: <action_name>
or, when you have enough information:
  Final Answer: <concise answer based on observations>

Rules:
- Only use action names from the available list.
- Prefer actions that haven't been run yet.
- Stop when observations cover the question fully.
- Never invent numbers; refer only to observations.
"""


def _llm_thought(question: str, observations: list[str],
                 engine: Any, model: str) -> tuple[str, str | None]:
    """
    Ask the LLM for the next Thought + Action (or Final Answer).

    Returns:
        (thought_text, action_name)  — action_name is None if LLM says Final Answer.
    """
    avail = ", ".join(_ACTION_PATTERNS.keys())
    system = _REACT_SYSTEM.format(actions=avail)

    history = ""
    if observations:
        history = "\n\nObservations so far:\n" + "\n---\n".join(
            f"[{i+1}] {o[:400]}" for i, o in enumerate(observations)
        )

    user_msg = f"Question: {question}{history}\n\nWhat next?"
    messages = [
        {"role": "system", "content": system},
        {"role": "user",   "content": user_msg},
    ]
    try:
        raw = engine.generate(messages, model, temperature=0.1, max_tokens=200)
    except Exception:   # noqa: BLE001
        return "", None

    # parse "Thought: ... \n Action: ..."
    thought_m = re.search(r"Thought:\s*(.+?)(?:\n|Action:|Final)", raw, re.DOTALL)
    action_m  = re.search(r"Action:\s*(\w+)", raw)
    final_m   = re.search(r"Final\s+Answer:\s*(.+)", raw, re.DOTALL)

    if final_m:
        return final_m.group(1).strip(), None
    thought = thought_m.group(1).strip() if thought_m else ""
    action  = action_m.group(1).strip().lower() if action_m else None
    # validate action name
    if action and action not in _ACTION_PATTERNS:
        action = None
    return thought, action


# ── Action executor ──────────────────────────────────────────────────────────

def _run_action(conn: Any, action: str, question: str) -> str | None:
    """Dispatch an action name to the right engine builder."""
    from . import engine as eng  # late import to avoid circulars
    # map action → builder function
    builder_map = {
        "kpis":          eng._answer_kpis,
        "forecast":      eng._answer_forecast,
        "waterfall":     eng._answer_waterfall,
        "top_bottom":    eng._answer_top_bottom,
        "agent_ranking": eng._answer_agent_ranking,
        "pattern":       eng._answer_pattern,
        "channel_fcr":   eng._answer_channel_fcr,
        "velocity":      eng._answer_velocity,
        "toxic_combos":  eng._answer_toxic_combos,
        "winback":       eng._answer_winback,
        "severity":      eng._answer_severity,
        "cohort":        eng._answer_cohort,
        "compare":       eng._answer_compare,
        "print_top":     eng._answer_print_top,
        "detractors":    eng._answer_detractors,
        "trend":         eng._answer_trend,
        "segments":      eng._answer_segments,
        "drivers":       eng._answer_drivers,
        "summary":       eng._answer_summary,
        "stats":         eng._answer_stats,
        "repeat":        eng._answer_repeat,
        "alerts":        eng._answer_alerts,
        "export":        eng._answer_export,
    }
    builder = builder_map.get(action)
    if builder is None:
        return None
    try:
        return builder(conn, question.lower())
    except Exception:   # noqa: BLE001
        return None


# ── Public API ────────────────────────────────────────────────────────────────

def is_complex(question: str) -> bool:
    """Return True if the question has explicit multi-step connector words.

    We require an explicit connector rather than counting overlapping regex
    matches (a single question like "show kpis" can match several patterns).
    """
    return bool(re.search(
        r"\bthen\b|\bafter\s+that\b|\bmoreover\b|\bfinally\b"
        r"|\bfollowed\s+by\b|\bnext\s+show\b|\bnext\s+get\b",
        question.lower(),
    ))


def run(conn: Any, question: str,
        llm_engine: Any = None, model: str | None = None,
        verbose: bool = False) -> str:
    """
    Run the ReAct loop for a (possibly multi-step) question.

    Args:
        conn:        SQLite connection (Roma's DB).
        question:    The user's natural-language question.
        llm_engine:  Optional LLMEngine instance (from llm.py); enables
                     LLM-guided Thought steps.
        model:       Model name to use with llm_engine.
        verbose:     If True, emit Thought/Action/Observation trace to stdout.

    Returns:
        A single combined answer string.
    """
    observations: list[str] = []
    done_actions: set[str] = set()

    # Choose planning mode
    use_llm = (llm_engine is not None and model is not None)

    if use_llm:
        steps = []  # LLM decides dynamically
    else:
        steps = _plan_steps(question)

    thought_calls = 0

    for step_i in range(MAX_STEPS):
        # ── decide next action ─────────────────────────────────────────────
        if use_llm and thought_calls < THOUGHT_BUDGET:
            thought, action = _llm_thought(
                question, observations, llm_engine, model
            )
            thought_calls += 1
            if verbose and thought:
                print(f"\n  [ReAct] Thought: {thought}")
            if action is None:
                # LLM gave a Final Answer inside thought
                if thought:
                    observations.append(thought)
                break
        else:
            # keyword planner
            remaining = [s for s in steps if s not in done_actions]
            if not remaining:
                break
            action = remaining[0]
            if verbose:
                print(f"\n  [ReAct] Action: {action}")

        if action in done_actions:
            # avoid infinite loops
            break
        done_actions.add(action)

        # ── run the action ─────────────────────────────────────────────────
        obs = _run_action(conn, action, question)
        if verbose:
            preview = (obs or "")[:120].replace("\n", " ")
            print(f"  [ReAct] Observation: {preview}")

        if obs:
            observations.append(obs)

        # update steps list for keyword planner (add newly triggered actions)
        if not use_llm and obs:
            for new_act in _detect_actions(obs):
                if new_act not in done_actions and new_act not in steps:
                    steps.append(new_act)

    if not observations:
        return ""

    if len(observations) == 1:
        return observations[0]

    # Combine multiple observations into a structured report
    parts = []
    for i, obs in enumerate(observations, 1):
        header = f"── Step {i} ─────────────────────────────────────────────"
        parts.append(f"{header}\n{obs}")
    return "\n\n".join(parts)
